--- #YAML:1.0
name:                POE-Filter-SSL
version:             0.22
abstract:            The easiest and flexiblest way to SSL in POE!
license:             ~
author:              
    - Markus Mueller <privi@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTTP::Status:                  0
    Net::SSLeay:                   1.32
    POE::Filter::HTTPD:            0
    POE::Filter::Stackable:        0
    POE::Wheel::ReadWrite:         0
    Test::More:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
